version: "3.8"
services:
        osm:
                build: ./osm
                env_file:
                        - osm.env
                secrets:
                        - db_password
                volumes:
                        - "./imposm:/var/lib/imposm"
                depends_on:
                        - postgis
        postgis:
                image: postgis/postgis:13-3.1-alpine
                env_file:
                        - postgis.env
                secrets:
                        - db_password
                volumes:
                        - "./postgres/data:/var/lib/postgresql/data"
                        - "./postgres/initdb:/docker-entrypoint-initdb.d/"
                ports:
                        - "5432:5432"
secrets:
        db_password:
                file: ./db_password
